project_id = "nqywnfgpwqpczesjkwtp"

[functions.programs]
verify_jwt = false

[functions.support]
verify_jwt = false

[functions.resources]
verify_jwt = true

[functions.register-player]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.generate-feedback-prompt]
verify_jwt = true

[functions.admin-users]
verify_jwt = false