// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-upcoming-games.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_upcoming_games_default = defineTool({
  name: "list_upcoming_games",
  title: "List upcoming games",
  description: "List upcoming CDBL games ordered by date. Optionally filter by division name (e.g. 'Pinto', 'Mustang', '10U'), team name, or limit.",
  inputSchema: {
    division: z.string().optional().describe("Division name substring to filter by."),
    team: z.string().optional().describe("Team name substring to filter by."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ division, team, limit }, ctx) => {
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await client(ctx).from("games").select(
      "id, game_date, game_time, status, home_team:home_team_id(name), away_team:away_team_id(name), venue:venue_id(name), division:division_id(name)"
    ).gte("game_date", today).neq("status", "cancelled").order("game_date", { ascending: true }).order("game_time", { ascending: true }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let rows = data ?? [];
    if (division) {
      const q = division.toLowerCase();
      rows = rows.filter((r) => r.division?.name?.toLowerCase().includes(q));
    }
    if (team) {
      const q = team.toLowerCase();
      rows = rows.filter(
        (r) => r.home_team?.name?.toLowerCase().includes(q) || r.away_team?.name?.toLowerCase().includes(q)
      );
    }
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { games: rows }
    };
  }
});

// src/lib/mcp/tools/list-facilities.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_facilities_default = defineTool2({
  name: "list_facilities",
  title: "List facilities and field status",
  description: "Return CDBL facilities (Stonecrest, Plato, Burlington, etc.) with each field's current open/closed status and any status note.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const { data, error } = await client2(ctx).from("venues").select("id, name, address, venue_fields(id, name, status, status_note)").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { facilities: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-faqs.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.75.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_faqs_default = defineTool3({
  name: "search_faqs",
  title: "Search CDBL FAQs",
  description: "Search Frequently Asked Questions by keyword. Returns matching question/answer pairs.",
  inputSchema: {
    query: z2.string().min(1).describe("Keyword or phrase to search for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query }, ctx) => {
    const { data, error } = await client3(ctx).from("faqs").select("id, question, answer, category").or(`question.ilike.%${query}%,answer.ilike.%${query}%`).order("display_order").limit(20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { faqs: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nqywnfgpwqpczesjkwtp";
var mcp_default = defineMcp({
  name: "cdbl-mcp",
  title: "CDBL Baseball",
  version: "0.1.0",
  instructions: "Tools for the Central District Baseball League (CDBL) website. Use `list_upcoming_games` for the schedule, `list_facilities` for field/facility status, and `search_faqs` for parent/coach questions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_upcoming_games_default, list_facilities_default, search_faqs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
